title: Voiresa's HCI Page
page-top-title: Voiresa
top-section-bg-text: University of Copenhagen
home-subtitle: Voiresa&ensp;|&ensp;YichengFeng
copyright-text: '&copy; Voiresa 2025-2026. All Rights Reserved.'
